version: "1.0"

networks:
  rabbit:

services:
  rabbit-1: &rabbitmq
    image: rabbitmq:3.8-management
    hostname: rabbit-1
    container_name: rabbit-1
    networks:
      - "rabbit"
    environment:
      RABBITMQ_CONFIG_FILE: /config/rabbitmq
      RABBITMQ_ERLANG_COOKIE: rabbit-cluster
    volumes:
      - ./rabbit-1/:/config/
    ports:
      - "8083:15692"

  rabbit-2:
    <<: *rabbitmq
    hostname: rabbit-2
    container_name: rabbit-2
    volumes:
      - ./rabbit-2/:/config/
    ports:
      - "8086:15692"

  rabbit-3:
    <<: *rabbitmq
    hostname: rabbit-3
    container_name: rabbit-3
    volumes:
      - ./rabbit-3/:/config/
    ports:
      - "8089:15692"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  haproxy:
    image: haproxy:1.7
    networks:
      - "rabbit"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbit-1
      - rabbit-2
      - rabbit-3
    ports:
      - 15672:15672
      - 5672:5672
