{
 "title": "RabbitMQ-Overview",
 "description": "A new RabbitMQ Management Overview",
 "tags": [ "rabbitmq-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(rabbitmq_identity_info, job)"
    }
   },
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{job=~\"$job\"}, rabbitmq_cluster)"
    }
   },
   {
    "name": "rabbitmq_node",
    "label": "RabbitMQ Node",
    "query": {
     "query": "label_values(rabbitmq_identity_info{job=~\"$job\",rabbitmq_cluster=~\"$rabbitmq_cluster\"}, rabbitmq_node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latência",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "perftest_latency_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Publicações",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_channel_messages_published_total",
     "legendFormat": "Node {{service}}"
    }
   ]
  },
  {
   "title": "Consumidores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queue_consumers", "legendFormat": "Node {{service}}" }
   ]
  },
  {
   "title": "Mensagens publicadas / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "perftest_published", "legendFormat": "Publicações / s" }
   ]
  },
  {
   "title": "Mensagens consumidas / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "perftest_consumed", "legendFormat": "Mensagens / s" }
   ]
  },
  {
   "title": "NODES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rabbitmq_build_info{job=~\"$job\"} * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", rabbitmq_node=~\"$rabbitmq_node\",job=~\"$job\"}"
    }
   ]
  }
 ]
}